#syntactical error

# print("Hello World)


#logcal error runs th code but do not give expected output

#run time error
# while True:
#     try:
#         x = int(input("Please enter a number: "))
#         print(x/0)
#         break
#     except ValueError:
#         print("Oops!  That was no valid number.  Try again...")

#         #run time error results sudden termination of program
#         # run time error is called exception



try:
    #risky code
    #code that can throw error
    pass
except:
    pass



